on: pull_request
name: Changelog Reminder
jobs:
  remind:
    name: Changelog Reminder
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Changelog Reminder
      uses: peterjgrainger/action-changelog-reminder@v1.2.0
      with:
        changelog_regex: '/HISTORY\/.*\/*.yml'
        customPrMessage: 'Remember to add an entry to the HISTORY!'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
